### ISSUE TITLE
Unable to update product from Stock Entries list. 

### ISSUE THREAD

**Issue by miki3421** [linuxserver/docker-grocy#33]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

I'm trying to update the price of the products purchased from the stock entry list and the price is not updating. In the journal is present the transaction however the field price still on 0. If i'm entering form the purchase function is working perfectly.  

I've just noticed that all the fields are not working. I tried also quantity and I have the same result.

## Expected Behavior

price updated correctly

## Current Behavior

price not updated

## Steps to Reproduce

1. Open stock Entries list
2. Edit one of the entries
3. Set the correct price
3. Press Ok
4. Press Close
5. price not updated

## Environment
**OS:** Raspeberry Pi4 with Rasbian 
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)

The same command that there is in the instruction.

**Comment by mountainsandcode** [comment]
This issue has been fixed in https://github.com/grocy/grocy/issues/1268 and will therefore be closed in the next release

**Comment by miki3421** [comment]
@mountainsandcode  I've updated yesterday to the last version and still not possibile. 
Witch version I need to wait? Thanks

**Comment by mountainsandcode** [comment]
Yesterday was just an update to the docker container (adding a missing library), we need to wait for a new release of grocy, then the image will be updated soon after that.

**Comment by miki3421** [comment]
Thanks @mountainsandcode i'm closing the issue in that case.
